openapi: 3.1.0
info:
  title: Column Preference API
  version: "0.1.0"
  description: |
    Contracts for managing dataset-specific search result column preferences.
servers:
  - url: http://localhost:8501/api
paths:
  /preferences/columns:
    get:
      summary: Retrieve the saved column preference for a dataset.
      tags: [ColumnPreferences]
      parameters:
        - name: datasetId
          in: query
          required: true
          schema:
            type: string
            format: uuid
        - name: userId
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Preference found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ColumnPreference"
        "404":
          description: No preference stored for this dataset/user combination.
    put:
      summary: Create or update the column preference for a dataset.
      tags: [ColumnPreferences]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateColumnPreferenceRequest"
      responses:
        "200":
          description: Preference saved successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ColumnPreference"
        "400":
          description: Invalid selection (e.g., exceeds maximum columns).
    delete:
      summary: Remove a stored column preference and revert to defaults.
      tags: [ColumnPreferences]
      parameters:
        - name: datasetId
          in: query
          required: true
          schema:
            type: string
            format: uuid
        - name: userId
          in: query
          required: false
          schema:
            type: string
      responses:
        "204":
          description: Preference removed.
  /preferences/columns/catalog:
    get:
      summary: List displayable columns available for a dataset.
      tags: [ColumnPreferences]
      parameters:
        - name: datasetId
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Columns available for selection.
          content:
            application/json:
              schema:
                type: object
                properties:
                  datasetId:
                    type: string
                    format: uuid
                  columns:
                    type: array
                    items:
                      $ref: "#/components/schemas/DisplayableColumn"

components:
  schemas:
    ColumnPreference:
      type: object
      properties:
        datasetId:
          type: string
          format: uuid
        userId:
          type: string
          nullable: true
        selectedColumns:
          type: array
          items:
            $ref: "#/components/schemas/SelectedColumn"
        maxColumns:
          type: integer
          minimum: 1
          maximum: 10
        updatedAt:
          type: string
          format: date-time
    SelectedColumn:
      type: object
      properties:
        columnName:
          type: string
        displayLabel:
          type: string
        position:
          type: integer
          minimum: 0
      required: [columnName, displayLabel, position]
    DisplayableColumn:
      type: object
      properties:
        columnName:
          type: string
        displayLabel:
          type: string
        dataType:
          type: string
        isAvailable:
          type: boolean
        lastSeenAt:
          type: string
          format: date-time
      required: [columnName, displayLabel, dataType, isAvailable]
    UpdateColumnPreferenceRequest:
      type: object
      properties:
        datasetId:
          type: string
          format: uuid
        userId:
          type: string
          nullable: true
        selectedColumns:
          type: array
          minItems: 0
          maxItems: 10
          items:
            $ref: "#/components/schemas/SelectedColumn"
        maxColumns:
          type: integer
          minimum: 1
          maximum: 10
      required: [datasetId, selectedColumns]
